[package]
name = "mokaccino_py"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "mokaccino_py"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.27.0"
mokaccino = "0.3.0"

